### ISSUE TITLE
Setup initial infrastructure for using it as sublibrary in seqan3

### ISSUE THREAD

**Issue by rrahn** [seqan/hibf_lib#12]
We want to use this project as the initial sublibrary included into seqan3.
For this we need to figure out some things first. An initial brainstorming can be found here: https://github.com/seqan/product_backlog/issues/395

### Todo

- [ ] Check out how recursive git clone works with circular dependency: hibf_lib -> seqan3 -> hibf_lib
- [ ] In case this works well, we can let the cmake backbone live in seqan3 for the moment, otherwise the cmake backbone should be ported to the app-template and seqan3 derives from the app-template.
- [ ] test how well hibf_lib can be integrated into seqan3 interface. search, index creation, accessor functions etc. (as a prototype to get a feeling for all other libs) -> to make a well educated decision
